#!/usr/bin/env bash
# Script to build JackPiOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "This is an example module, install and set up what you need here!"
echo "$JACKPI_VAR"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /


apt-get update
debian_frontend=noninteractive apt-get install -y jackd2
