version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    container_name: ${DISTRO_NAME}-build
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
      #- /home/guysoft/CustomPiOS:/CustomPiOS/src
    devices:
      - /dev/loop-control
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: v2tec/watchtower
    container_name: custompios-watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --cleanup --label-enable --interval 30
    restart: always
